[build]
  command = "npm run build"
  functions = "dist/netlify/functions"

[functions]
  included_files = [
    "node_modules/.prisma/client/**"
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200